# This is a basic workflow to help you get started with Actions

name: Caller Demoo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branchh
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  calling-workflow-1:
    name: Calling workflow 11
    uses: hirenrparghi/Reusable-workflow/.github/workflows/first-gh-actions.yml@main
    with:
      version: 'v2.1.4'
